### ISSUE TITLE
Error messages in script windows dont show script window line number

### ISSUE THREAD

**Issue by SimonLentner** [cube-codes/cube-codes-website#78]
if this is possible by simply passing on the error message corrently, it would be a great help in debugging

**Comment by lukaslentner** [comment]
You can always `throw new Error('ddd')` and at least in Chrome you get a good stacktrace:
```
[10:28:49] Program failed with an error: ddd
Stack: Error: ddd
    at self.program (eval at  (https://ide.cube.codes/worker/dist/browser/browser.js:89705:18), :4:7)
    at ExecutionContext. (https://ide.cube.codes/worker/dist/browser/browser.js:89708:31)
    at Generator.next ()
    at fulfilled (https://ide.cube.codes/worker/dist/browser/browser.js:89664:59)
```

Beware that it says: Line 4, Column 7.
You must always deduct 3 from the line number! (I do not know why)...

For this deduction there is already a issue #32
